const TRANSACTION_URL = 'https://blockstream.info/tx/$sourceId';
const RECEIPT_VERIFICATION_URL = 'https://share.woleet.io/api/receipt/verify';
const RECEIPT_IDENTITY_URL = 'https://identity.woleet.io/identity';

/**
 * Proof verifier widget constants
 * @type {string}
 */
const PROOF_VERIFIER_WIDGET_ID = 'proof-verifier-widget';
const PROOF_VERIFIER_WIDGET_TYPE = 'PROOF_VERIFIER_WIDGET';
const PROOF_VERIFIER_MODE_ICON = 'icon';
const PROOF_VERIFIER_MODE_BANNER = 'banner';
const PROOF_VERIFIER_MODE_PANEL = 'panel';

const PROOF_VERIFIER_DEFAULT_MODE = PROOF_VERIFIER_MODE_ICON;
const PROOF_VERIFIER_WIDGET_MODES = [
  PROOF_VERIFIER_MODE_ICON,
  PROOF_VERIFIER_MODE_BANNER,
  PROOF_VERIFIER_MODE_PANEL
];

export default {
  PROOF_VERIFIER_WIDGET_ID, /* export proof-verifier-widget constants */
  PROOF_VERIFIER_WIDGET_TYPE,
  PROOF_VERIFIER_DEFAULT_MODE,
  PROOF_VERIFIER_WIDGET_MODES,
  PROOF_VERIFIER_MODE_ICON,
  PROOF_VERIFIER_MODE_BANNER,
  PROOF_VERIFIER_MODE_PANEL,

  RECEIPT_VERIFICATION_URL,
  RECEIPT_IDENTITY_URL,
  TRANSACTION_URL
};
