/**
 * Widget constants and default values
 * */
const WIDGET_MODE_ICON = 'ICON';
const WIDGET_MODE_BANNER = 'BANNER';
const WIDGET_MODE_FULL = 'FULL';

const DEFAULT_WIDGET_LANGUAGE = document.documentElement.lang;

const DEFAULT_WIDGET_MODE = WIDGET_MODE_ICON;
const AVAILABLE_WIDGET_MODES = [WIDGET_MODE_ICON, WIDGET_MODE_BANNER, WIDGET_MODE_FULL];

const FILE_HASHER_WIDGET_TYPE = 'FILE_HASHER_WIDGET';
const PROOF_VERIFIER_WIDGET_TYPE = 'PROOF_VERIFIER_WIDGET';

const FILE_HASHER_WIDGET_ID = 'file-hasher-widget';

const TIMINGS = {
  error_displaying: 2000
};

const PROXY_URL = 'http://localhost:3000/download?url=';

export default {
  TIMINGS,
  PROXY_URL,
  DEFAULT_WIDGET_MODE,
  WIDGET_MODE_ICON,
  WIDGET_MODE_BANNER,
  WIDGET_MODE_FULL,
  AVAILABLE_WIDGET_MODES,
  FILE_HASHER_WIDGET_TYPE,
  PROOF_VERIFIER_WIDGET_TYPE,
  FILE_HASHER_WIDGET_ID,
  DEFAULT_WIDGET_LANGUAGE
};
